Connect to cloudwatch later in __init__
This avoids an exception on shutdown if the connection to CloudWatch
fails (e.g. because of a botocore.exceptions.NoRegionError).

    Error in sys.exitfunc:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
       func(*targs, **kargs)
    File "/usr/lib/python2.7/logging/__init__.py", line 1661, in shutdown
       h.flush()
    File "/usr/lib/python2.7/dist-packages/watchtower/__init__.py", line 158, in flush
       for q in self.queues.values():
    AttributeError: 'CloudWatchLogHandler' object has no attribute 'queues'